### Get all videos
GET http://localhost:9090/get-videos
Accept: application/json

### Create video
POST http://localhost:9090/create-video
Content-Type: application/json
Accept: application/json

{
  "name": "Second video"
}