### Get all videos
GET http://localhost:9090/get-videos
Accept: application/json

### Create video
POST http://localhost:9090/create-video
Content-Type: application/json
Accept: application/json

{
  "name": "Second video"
}

### Search video by name
GET http://localhost:9090/search-by-name?name=Second%20Video
Accept: application/json

### Search video by id
GET http://localhost:9090/search-by-id?id=1
Accept: application/json